language: objective-c
xcode_workspace: swiflection.xcworkspace
before_script:
- ./scripts/travis/add-key.sh
after_script:
- ./scripts/travis/remove-key.sh
rvm: 2.1.4 
osx_image: xcode61
  - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in account/profile/iOSTeam_Provisioning_Profile_combrightdigit.mobileprovision.enc-d -a -out account/profile/iOSTeam_Provisioning_Profile_combrightdigit.mobileprovision.enc
  - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in account/certs/dev.cer.enc -d -a -out account/certs/dev.cer
  - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in account/certs/dev.p12.enc -d -a -out account/certs/dev.p12
matrix:
  include:
    - xcode_scheme: Swiflection_IOS
      xcode_sdk: iphoneos
    - xcode_scheme: Swiflection_IOS
      xcode_sdk: iphoneos8.1
    - xcode_scheme: Swiflection_IOS
      xcode_sdk: iphonesimulator8.1
    - xcode_scheme: Swiflection_OSX
      xcode_sdk: macosx
    - xcode_scheme: Swiflection_OSX
      xcode_sdk: macosx10.10
env:
  global:  
  - 'DEVELOPER_NAME="iPhone Developer: Leo Dion (5VZ4KT69B9)"'
  - PROFILE_NAME="iOSTeam_Provisioning_Profile_combrightdigit"
  - secure: EM6gOXtFKJmvANHD4OHG5cSIuJe1omIiiz1c4oqlduXuOiDINZw19ci3WrNpR9cAibeUNkKvw21BQR1BAf6eB2nsVglHXDW5d1KkQbmgJYiy3wWzyuZfXT5ES+y0BzBUIeFKzmxD0qGa+iiPtz4KXxwryJwd2Hy9lqFtY9BRWpw=
  - secure: l/OocnTNpJrx5nE/hSUyWm6Fj5VmL2XDVoPEeRwAajLNbXs389+ueeWwgkgUfAFrAxbPqTgrpWbgM8aKcPryZO2RrXOYiAhPH1b1vj71NDUYYJDT91p56ZuGkzhLASS67nT2g3REbjtEM4f5xbsEn5eZWKm/a9D1zlXOAxeasLI=
