language: objective-c
osx_image: xcode9
xcode_project: Swiflection.xcodeproj
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE="Swiflection.xcodeproj"
  - IOS_FRAMEWORK_SCHEME="SwiftVer iOS"
  - IOS_SDK=iphonesimulator10.0
  - EXAMPLE_SCHEME="iOS Example"
  - POD_LINT="YES"
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 7 Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     POD_LINT="NO"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -list
  - ./build.sh
# before_script:
# - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in account/profile/iOSTeam_Provisioning_Profile_combrightdigit.mobileprovision.enc -d -a -out account/profile/iOSTeam_Provisioning_Profile_combrightdigit.mobileprovision
# - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in account/certs/dev.cer.enc -d -a -out account/certs/dev.cer
# - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in account/certs/dev.p12.enc -d -a -out account/certs/dev.p12
# - ./scripts/add_key.sh
# after_script:
# - ./scripts/remove_key.sh
# rvm: 2.1.4
# env:
#   global:
#   - 'DEVELOPER_NAME="iPhone Developer: Leo Dion (5VZ4KT69B9)"'
#   - PROFILE_NAME="iOSTeam_Provisioning_Profile_combrightdigit"
#   - secure: EM6gOXtFKJmvANHD4OHG5cSIuJe1omIiiz1c4oqlduXuOiDINZw19ci3WrNpR9cAibeUNkKvw21BQR1BAf6eB2nsVglHXDW5d1KkQbmgJYiy3wWzyuZfXT5ES+y0BzBUIeFKzmxD0qGa+iiPtz4KXxwryJwd2Hy9lqFtY9BRWpw=
#   - secure: l/OocnTNpJrx5nE/hSUyWm6Fj5VmL2XDVoPEeRwAajLNbXs389+ueeWwgkgUfAFrAxbPqTgrpWbgM8aKcPryZO2RrXOYiAhPH1b1vj71NDUYYJDT91p56ZuGkzhLASS67nT2g3REbjtEM4f5xbsEn5eZWKm/a9D1zlXOAxeasLI=
