language: objective-c
xcode_workspace: swiflection.xcworkspace
xcode_scheme: [Swiflection_IOS, Swiflection_OSX]
osx_image: xcode61
xcode_sdk: [iphonesimulator7.0 ,iphonesimulator7.1, iphonesimulator8.0, iphonesimulator8.1]
